FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# TODO: Install dependencies
# Hint: Use npm install

COPY . .

# TODO: Expose port
# Hint: Use EXPOSE 3001

# TODO: Start the application
# Hint: Use CMD ["npm", "start"] 