FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# TODO: Install dependencies
# Hint: Use npm install

COPY . .

# TODO: Build the application
# Hint: Use npm run build

# TODO: Install serve to run the built application
# Hint: Use npm install -g serve

# TODO: Expose port
# Hint: Use EXPOSE 3000

# TODO: Start the application
# Hint: Use CMD ["serve", "-s", "build", "-l", "3000"] 